spring:
  datasource:
    url: jdbc:mysql://root:root@db:3306/chat?createDatabaseIfNotExist=true
    driver-class-name: com.mysql.cj.jdbc.Driver

  data:
    mongodb:
      uri: mongodb://root:root@mongo:27017
      database: chat-app

    redis:
      host: redis
      port: 6379

  jpa:
    hibernate:
      ddl-auto: update

  sql:
    init:
      mode: never
