spring:
  datasource:
#    url: jdbc:mysql://root:root@localhost:3306/chat?createDatabaseIfNotExist=true
    url: jdbc:mysql://root:root@db:3306/chat?createDatabaseIfNotExist=true
    driver-class-name: com.mysql.cj.jdbc.Driver

  data:
    mongodb:
#      uri: mongodb://root:root@localhost:27017
      uri: mongodb://root:root@mongo:27017
      database: chat-app

  jpa:
    hibernate:
      ddl-auto: update

    open-in-view: false # sse 사용으로 JPA DB connection 반환을 메서드 반환 시점에 진행하기 위해 설정

  sql:
    init:
      mode: never
