spring:
  datasource:
    url: jdbc:h2:~/test
    username: sa
    password:
    driver-class-name: org.h2.Driver

  h2:
    console:
      enabled: true

  jpa:
    # sse 사용으로 JPA DB connection 반환을 메서드 반환 시점에 진행하기 위해 설정
    open-in-view: false

  sql:
    init:
      mode: always

  data:
    mongodb:
      uri: mongodb://localhost:27017/chat



---
spring:
  profiles:
    active: dev

  jpa:
    hibernate:
      ddl-auto: create-drop
    defer-datasource-initialization: true

logging:
  level:
    web: debug