spring:
  datasource:
    url: jdbc:mysql://root:root@localhost:3306/chat?createDatabaseIfNotExist=true
#    url: jdbc:mysql://root:root@local:3306/chat?createDatabaseIfNotExist=true
    driver-class-name: com.mysql.cj.jdbc.Driver

  data:
    mongodb:
      uri: mongodb://root:root@localhost:27017
#      uri: mongodb://root:root@mongo:27017
      database: chat-app
